name: Tests

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  CI: true
  NODE_VERSION: 14

jobs:
  test:
    name: Jest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: node --version
      - run: npm --version

      - name: NPM Install
        run: npm ci

      - name: Run Tests
        run: npm run test --if-present
